### ISSUE TITLE
Implement Task Iterization

### ISSUE THREAD

**Issue by fiona-june-leathers** [Cloud-Harvest/CloudHarvestCoreTasks#13]
We currently have the `ForEachTask`, but this is needlessly complicated. Instead, we will implement a new directive which provides the same functionality. Example:

```yaml
my_task:
  name: My iteration task 'item.name'
  iterate: 
    variable: var.my_data
    # insert_tasks_at_position:
    # insert_tasks_before_name:
    # insert_tasks_after_name:
```

Here, `item` stands in for the iteration object which is parsed over [the new templating engine](https://github.com/Cloud-Harvest/CloudHarvestCoreTasks/issues/12).

Variable starting with `var` access the parent TaskChain's `variables` while `item` access the iterable.
