### ISSUE TITLE
Create Task Parts

### ISSUE THREAD

**Issue by fiona-june-leathers** [Cloud-Harvest/CloudHarvestCoreTasks#25]
Presently, everything in Harvest has to be written manually and duplicated for each object of record.

Improving the task factories to accept a `parts` task category will allow us to write components which can function similarly to `yaml` anchors. 

```yaml


```

```yaml
tasks:
  - part:
      part_name: aws.list_resource_tags
```
