### ISSUE TITLE
HarvestUpdateTask ensures indexes

### ISSUE THREAD

**Issue by fiona-june-leathers** [Cloud-Harvest/CloudHarvestCoreTasks#28]
Indexes are theoretically handled by the API, but there's no thread/job to manage it. We may benefit putting index creation inside the Service templates which can better target exactly what needs to be indexed for a given collection:

```yaml
harvest:
  name: get data
  description: something
  unique_identifier: Arn
  indexes:
    - index_name:
        keys:
          - KeyA
          - KeyB
```
