### ISSUE TITLE
Tasks should be able to spawn awaitable tasks agents can pick up

### ISSUE THREAD

**Issue by fiona-june-leathers** [Cloud-Harvest/CloudHarvestCoreTasks#30]
In order to perform work like `aws.rds.logs-download` (or any other workload which involves sending Tasks back to the agent), we need a task which calls the name of another task and supplies any relevant variables.

Why? The Harvest Agent has been designed to restrict which PSTARs it handles. To perform a download of RDS logs, it would be necessary to take a list of arbitrary RDS Instances and perform `AwsTasks` against them.

However, the calling Agent may not have access to perform `AwsTask` against a given PSTAR (most likely Account or Region). Therefore, the work must be queued via the Api, completed by an Agent, and the results returned to the original task. 

```yaml
tasks:
  - enqueue:
      name: Get RDS Logs
      template:
        name: aws.rds._get_logs    # hidden report
        type: report
      variables:
        account: item.Harvest.AccountId
        region: item.Harvest.Region
        identifier: item.DBInstanceIdentifier
        log_file_names: LogFileName
      iterate: var.matching_instances_and_filenames
      result_as:
        name: result
        mode: extend
```
