### ISSUE TITLE
Add the `on` parameter to `BaseTask`

### ISSUE THREAD

**Issue by fiona-june-leathers** [Cloud-Harvest/CloudHarvestCoreTasks#7]
This allows users to provide a `Task` which is performed following one of the four `on_` methods:

- [ ] Complete
- [x] Error
- [ ] Skip
- [x] Start (though this one seems unlikely it is added for completeness with the `on_` methods)

Expected behavior:
* Whenever the BaseTask enters the appropriate state, the provided `on` template is added to the next template position in the queue.

Example
```YAML
name: test
description: an example using an 'on' condition

tasks:
  - dummy:
      name: my dummy task
      on_complete:
        delay:
          name: my delay task
          delay_seconds: 5

```
