### ISSUE TITLE
Add `retry` directive to `BaseTask`

### ISSUE THREAD

**Issue by fiona-june-leathers** [Cloud-Harvest/CloudHarvestCoreTasks#9]
Allows a task to be retried `n` times until it completes successfully. This is helpful when interfacing with resources which may not be readily available or experience throttling, such as external APIs.

# Directive Arguments

Field                 | Default | Description
----------------------|---------|------------------------------------------------------------
`max_attempts`        | `10`    | Prevents the Task from retrying indefinitely.
`wait_seconds`        | `5.0`   | The time to block the Task until it should try again.
`when_error_like`     | `None`  | Retry when the error matches the provided regex expression.
`when_error_not_like` | `None`  | Retry when the error does _not_ match the provided regex expression.

When `when_error_like` and `when_error_not_like` are provided, they are treated as an `OR` expression. Therefore, the task will try again if any of the `when_error` conditions is met.

# Example

```yaml
task:
  name: my task
  description: an example of a task which contains the `retry` directive.
  retry:
    max_attempts: 10
    wait_seconds: 5
    when_error_like: 'regex.*expression'
    when_error_not_like: 'another.regex.*expression'
```
